name: Konflux Auto-merge
on:
  pull_request_target:
    paths:
      - 'Dockerfile'
      - '.pre-commit-config.yaml'
      - 'iqe-host-inventory-plugin/.pre-commit-config.yaml'
      - 'rpms.lock.yaml'

jobs:
  konflux-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'red-hat-konflux[bot]' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.AUTOMERGE_APP_ID }}
          private-key: ${{ secrets.AUTOMERGE_APP_PRIVATE_KEY }}
      - name: Enable auto-merge for Konflux PRs
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
